# Generated by Django 5.1.6 on 2025-03-05 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=250, null=True)),
                ('inception_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('max_investment_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
                ('capacity_total', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('risk_adjustor', models.DecimalField(decimal_places=1, default=None, max_digits=5, null=True)),
                ('discount_rate', models.DecimalField(decimal_places=1, default=0.15, max_digits=5)),
                ('draw_number', models.IntegerField(default=5)),
                ('draw_utilization', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('inception_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('irr', models.DecimalField(decimal_places=3, default=None, max_digits=7, null=True)),
                ('npv', models.DecimalField(decimal_places=3, default=None, max_digits=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='forecast_generator.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('technology', models.CharField(choices=[('solar', 'solar'), ('storage', 'Storage'), ('onshore wind', 'Onshore Wind'), ('Wind - Offshore', 'Wind - Offshore'), ('hydrogen', 'Hydrogen')], max_length=20)),
                ('market', models.CharField(choices=[('iso-ne', 'ISO-NE'), ('nyiso', 'NYISO'), ('pjm', 'PJM'), ('caiso', 'CAISO'), ('miso', 'MISO'), ('ercot', 'ERCOT')], default=None, max_length=10, null=True)),
                ('developer_fee', models.DecimalField(decimal_places=2, default=0.03, max_digits=7)),
                ('ntp', models.DateField()),
                ('cod', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='forecast_generator.portfolio')),
            ],
        ),
    ]
