# Generated by Django 5.1.6 on 2025-03-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnsModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=20, null=True)),
                ('category', models.CharField(choices=[('principal balance - bop', 'Principal Balance - BOP'), ('interest', 'Interest'), ('interest - uncapitalized', 'Interest - Uncapitalized'), ('interest - capitalized', 'Interest - Capitalized'), ('pik', 'Pik'), ('deposit refunds', 'Deposit Refunds'), ('commitment fee', 'Commitment Fee'), ('extension fee', 'Extension Fee'), ('origination fee', 'Origination Fee'), ('estimated closing costs', 'Estimated Closing Costs'), ('financing fee', 'Financing Fee'), ('incentive fee', 'Incentive Fee'), ('draws', 'Draws'), ('repayment', 'Repayment'), ('interest repayment', 'Interest Repayment'), ('principal balance - eop', 'Principal Balance - EOP'), ('incentive fee - pl', 'Incentive Fee - PL'), ('minimum moic', 'Minimum MOIC'), ('inflows', 'Inflows'), ('outflows', 'Outflows'), ('net', 'Net')], max_length=50, null=True)),
                ('project_informed', models.BooleanField(default=0, null=True)),
                ('proceed_category', models.CharField(choices=[('ntp proceed', 'NTP Proceed'), ('cod proceed', 'COD Proceed'), ('closing proceed', 'Closing Proceed'), ('maturity repayment', 'Maturity Repayment')], max_length=50, null=True)),
                ('data_status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('underwritten', 'Underwritten'), ('marked', 'Marked'), ('active - forecast', 'Active - Forecast'), ('archived - forecast', 'archived - Forecast'), ('actual', 'Actual'), ('target', 'Target')], default=None, max_length=50, null=True)),
                ('projection_source', models.CharField(choices=[('automated', 'Automated'), ('manual', 'Manual'), ('underwritten model', 'Underwritten Model'), ('pam model', 'PAM Model')], default=None, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('financial_solution', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='forecast_generator.financialio')),
            ],
        ),
    ]
